In [4]:
# import
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# scale the KPI columns using MinMaxScaler
df = pd.read_csv('Data/2022-2023_Football_Players_stats.csv')
df.head(4)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon/90,AerLost,AerDuels/90,AerWon%
0,1,Brenden Aaronson,USA,MFFW,Leeds United,Premier League,22,2000,20,19,...,2.54,0.51,0.0,0.0,0.00,4.86,0.34,1.19,1.53,22.2
1,2,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,35,1987,22,22,...,0.18,1.59,0.0,0.0,0.00,6.64,2.18,1.23,3.41,64.0
2,3,Himad Abdelli,FRA,MFFW,Angers,Ligue 1,23,1999,14,8,...,1.05,1.40,0.0,0.0,0.00,8.14,0.93,1.05,1.98,47.1
3,4,Salis Abdul Samed,GHA,MF,Lens,Ligue 1,22,2000,20,20,...,0.35,0.80,0.0,0.0,0.05,6.60,0.50,0.50,1.00,50.0